### ISSUE TITLE
adding height to root on CircularProgressbarWithChildren causes children to render incorrectly

### ISSUE THREAD

**Issue by KolbySisk** [kevinsqi/react-circular-progressbar#115]
### Summary of issue

When I set a height to the root container - `CircularProgressbarWithChildren__children` isn't rendered in the center of the circle. It's actually rendered far above.

The cause is this css line: `margin-top: -100%;` change it to `transform: translateY(-100%)` and you're good to go.

### Reproducible exam

https://stackblitz.com/edit/react-uhec1a

**Comment by kevinsqi** [comment]
Hi @KolbySisk! Thanks for the report and reproducible example.

While you can set `<CircularProgressbar styles={{ root: { height: 100 }}} />`, it's not intended to really correctly work that way - the styles are designed such that you specify the dimensions of the progressbar by setting the size of the parent container, instead of setting the size of the progressbar itself. This makes it more adaptable to responsive design, so that if you stick it in a CSS/bootstrap/etc grid column, it'll size itself automatically.

My suggestion for adding dimensions is to add a wrapper div with the width that you want to have:
https://stackblitz.com/edit/react-pdexgh?file=index.js

If it's not convenient to create wrapper divs each time, you can create a small wrapper component  that accepts a width prop:

```
function WidthProgressbar(props) {
  const { width, ...otherProps } = props;
  return (
    <div style={{ width: width }}>
      <CircularProgressbarWithChildren {...otherProps} />
    </div>
  );
}
```

Does this help get you what you need?

**Comment by kevinsqi** [comment]
@KolbySisk I hope the previous answer can help get you what you need - if it doesn't, please re-open and let me know!
